# Generated by Django 5.2.6 on 2025-10-24 01:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0001_initial'),
        ('recipes', '0012_recipe_date_added_recipe_times_made'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cartrecipe',
            old_name='quantity',
            new_name='serving_size',
        ),
        migrations.RemoveField(
            model_name='cartitem',
            name='ingredient',
        ),
        migrations.AlterField(
            model_name='cartitem',
            name='recipe_ingredient',
            field=models.ForeignKey(default=1.0, on_delete=django.db.models.deletion.CASCADE, to='recipes.ingredient'),
            preserve_default=False,
        ),
    ]
