# Generated by Django 5.2.6 on 2025-10-24 15:02

from django.db import migrations
from django.conf import settings


def cleanup_duplicate_carts(apps, schema_editor):
    """Remove duplicate carts, keeping the oldest one for each user."""
    Cart = apps.get_model('cart', 'Cart')
    app_label, model_name = settings.AUTH_USER_MODEL.split('.')
    User = apps.get_model(app_label, model_name)
    
    # Get all users who have multiple carts
    from django.db.models import Count
    users_with_multiple_carts = User.objects.annotate(
        cart_count=Count('cart')
    ).filter(cart_count__gt=1)
    
    for user in users_with_multiple_carts:
        # Get all carts for this user, ordered by creation date
        carts = Cart.objects.filter(user=user).order_by('created_at')
        
        # Keep the first (oldest) cart
        cart_to_keep = carts.first()
        
        # Delete all other carts
        carts.exclude(id=cart_to_keep.id).delete()


def reverse_cleanup_duplicate_carts(apps, schema_editor):
    """Reverse migration - nothing to do."""
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0002_rename_quantity_cartrecipe_serving_size_and_more'),
    ]

    operations = [
        migrations.RunPython(cleanup_duplicate_carts, reverse_cleanup_duplicate_carts),
    ]
