# Generated by Django 5.2.6 on 2025-11-14 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0007_orderhistory_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderhistory',
            name='instacart_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='orderhistory',
            name='top_recipe_image',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
