# Generated by Django 5.2.6 on 2025-10-12 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meal_calendar', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mealplan',
            name='breakfast',
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name='mealplan',
            name='dinner',
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name='mealplan',
            name='lunch',
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name='mealplan',
            name='snacks',
            field=models.JSONField(default=list),
        ),
    ]
