# Generated by Django 5.2.6

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0004_alter_ingredient_recipe_alter_step_recipe'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nutrient',
            name='recipe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nutrients', to='recipes.recipe'),
        ),
    ]