# Generated by Django 5.2.6 on 2025-10-18 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0007_recipe_source_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredient',
            name='name',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='unit',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='nutrient',
            name='macro',
            field=models.CharField(max_length=100),
        ),
    ]
