# Generated by Django 5.2.6 on 2025-10-18 20:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0007_fix_field_lengths'),
        ('recipes', '0008_alter_ingredient_name_alter_ingredient_unit_and_more'),
    ]

    operations = [
    ]
