# Generated by Django 5.2.6 on 2025-10-18 20:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0009_fix_description_field'),
        ('recipes', '0009_merge_20251018_2007'),
    ]

    operations = [
    ]
