# Generated by Django 5.2.6 on 2025-10-22 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0010_merge_20251018_2010'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='image_url',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='source_url',
            field=models.TextField(blank=True, null=True),
        ),
    ]
