# Generated by Django 5.2.6 on 2025-10-23 18:08

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0011_alter_recipe_image_url_alter_recipe_source_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='date_added',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='recipe',
            name='times_made',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
