# Generated by Django 5.2.6 on 2025-11-12 17:56

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0014_recipe_serves'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrendingRecipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week', models.CharField(db_index=True, max_length=7)),
                ('position', models.PositiveIntegerField()),
                ('spoonacular_id', models.IntegerField(db_index=True, unique=True)),
                ('title', models.CharField(max_length=500)),
                ('description', models.TextField(blank=True, null=True)),
                ('image_url', models.TextField(blank=True, null=True)),
                ('source_url', models.TextField(blank=True, null=True)),
                ('ready_in_minutes', models.PositiveIntegerField(blank=True, null=True)),
                ('servings', models.PositiveIntegerField(blank=True, null=True)),
                ('recipe_data', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('week_start_date', models.DateField(help_text='Start date of the week (Monday)')),
            ],
            options={
                'ordering': ['-week', 'position'],
                'indexes': [models.Index(fields=['week', 'position'], name='recipes_tre_week_feea24_idx'), models.Index(fields=['-week'], name='recipes_tre_week_718553_idx')],
                'unique_together': {('week', 'position')},
            },
        ),
    ]
