# Generated by Django 5.2.6 on 2025-11-13 16:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0015_trendingrecipe'),
    ]

    operations = [
        migrations.AddField(
            model_name='trendingrecipe',
            name='recipe',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='trending_recipe', to='recipes.recipe'),
        ),
    ]
