# Generated by Django 5.2.6 on 2025-11-13 16:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0016_trendingrecipe_recipe'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trendingrecipe',
            name='description',
        ),
        migrations.RemoveField(
            model_name='trendingrecipe',
            name='image_url',
        ),
        migrations.RemoveField(
            model_name='trendingrecipe',
            name='servings',
        ),
        migrations.RemoveField(
            model_name='trendingrecipe',
            name='source_url',
        ),
        migrations.RemoveField(
            model_name='trendingrecipe',
            name='title',
        ),
        migrations.AlterField(
            model_name='trendingrecipe',
            name='recipe',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='trending_recipe', to='recipes.recipe'),
        ),
    ]
