# Generated by Django 5.2.6 on 2025-11-14 03:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0016_ingredient_original_text'),
        ('recipes', '0017_remove_trendingrecipe_description_and_more'),
    ]

    operations = [
    ]
