# Generated by Django 5.2.6 on 2025-11-15 18:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0018_merge_20251114_0317'),
        ('recipes', '0020_add_is_trending_field'),
    ]

    operations = [
    ]
